def set_template(args):
    if args.template == 'SWINT_HSA_NSF':
        args.task = "VideoDeblur"
        args.model = "SWINT_HSA_NSF"
        args.n_sequence = 3
        args.patch_size = 200
        args.n_frames_per_video = 200
        args.n_feat = 32
        args.n_resblock = 3
        args.size_must_mode = 4
        args.loss = '1*L1+2*HEM'
        args.lr = 1e-4
        args.lr_decay = 200
        args.window_size = 5
        args.depths = [6, 6, 6, 6, 6, 6]
        args.embed_dim = 256
        args.num_heads = [8, 8, 8, 8, 8, 8]
        args.mlp_ratio = 2
        args.resi_connection = "1conv"
        args.data_train = 'DVD_NFS'
        args.data_test = 'DVD_NFS'
        args.batch_size = 12
        args.pre_train = '../experiment/swint_neighbour2mid_seq3/model/model_best.pt'
    elif args.template == 'SWINT_HSA_NSF_Offical':
        args.task = "VideoDeblur"
        args.model = "SWINT_HSA_NSF_Offical"
        args.n_sequence = 5
        args.patch_size = 200
        args.n_frames_per_video = 200
        args.n_feat = 32
        args.n_resblock = 3
        args.size_must_mode = 4
        args.loss = '1*L1+2*HEM'
        args.lr = 1e-4
        args.lr_decay = 200
        args.window_size = 5
        args.depths = [6, 6, 6, 6, 6, 6]
        args.embed_dim = 256
        args.num_heads = [8, 8, 8, 8, 8, 8]
        args.mlp_ratio = 2
        args.resi_connection = "1conv"
        args.dir_data = '/mnt/disk10T/shangwei/data/deblur/Random/train'
        args.dir_data_test = '/mnt/disk10T/shangwei/data/deblur/Random/val'
        args.batch_size = 12
        args.pre_train = '../experiment/swint_hsa_nsf/model/model_best.pt'
    elif args.template == 'SWINT_HSA_NSF_REDS':
        args.task = "VideoDeblur"
        args.model = "SWINT_HSA_NSF"
        args.n_sequence = 3
        args.patch_size = 200
        args.n_frames_per_video = 200
        args.n_feat = 32
        args.n_resblock = 3
        args.size_must_mode = 4
        args.loss = '1*L1+2*HEM'
        args.lr = 5e-5
        args.lr_decay = 200
        args.window_size = 5
        args.depths = [6, 6, 6, 6, 6, 6]
        args.embed_dim = 256
        args.num_heads = [8, 8, 8, 8, 8, 8]
        args.mlp_ratio = 2
        args.resi_connection = "1conv"
        args.data_train = 'DVD_NFS'
        args.data_test = 'DVD_NFS'
        args.batch_size = 12
        args.pre_train = '../experiment/swint_hsa_nsf/model/model_best.pt'
        args.dir_data = '/mnt/disk10T/shangwei/data/deblur/REDS_8x_Random/train'
        args.dir_data_test = '/mnt/disk10T/shangwei/data/deblur/REDS_8x_Random/val'
    elif args.template == 'SWINT_HSA_NSF_EVENT':
        args.task = "VideoDeblur"
        args.model = "SWINT_HSA_NSF_EVENT"
        args.n_sequence = 5
        args.patch_size = 200
        args.n_frames_per_video = 200
        args.n_feat = 32
        args.n_resblock = 3
        args.size_must_mode = 20
        args.loss = '1*L1+2*HEM'
        args.lr = 1e-4
        args.lr_decay = 20
        args.window_size = 5
        args.depths = [6, 6, 6, 6, 6, 6]
        args.embed_dim = 256
        args.num_heads = [8, 8, 8, 8, 8, 8]
        args.mlp_ratio = 2
        args.epochs = 50
        args.resi_connection = "1conv"
        args.data_train = 'DVD_EVENT'
        args.data_test = 'DVD_EVENT'
        args.batch_size = 10
        args.pre_train = '../experiment/swint_hsa_nsf_offical/model/model_best.pt'
        args.dir_data = '/mnt/disk10T/shangwei/data/deblur/CED/train'
        args.dir_data_test = '/mnt/disk10T/shangwei/data/deblur/CED/val'
        args.n_GPUs = 2
    elif args.template == 'SWINT_HSA_NSF_EVENT_GREY':
        args.task = "VideoDeblur"
        args.model = "SWINT_HSA_NSF_EVENT"
        args.n_sequence = 5
        args.patch_size = 180
        args.n_frames_per_video = 200
        args.n_feat = 32
        args.n_resblock = 3
        args.size_must_mode = 20
        args.loss = '1*L1+2*HEM'
        args.lr = 4e-5
        args.lr_decay = 20
        args.window_size = 5
        args.depths = [6, 6, 6, 6, 6, 6]
        args.embed_dim = 256
        args.num_heads = [8, 8, 8, 8, 8, 8]
        args.mlp_ratio = 2
        args.epochs = 50
        args.resi_connection = "1conv"
        args.data_train = 'DVD_EVENT_FUSION_GREY'
        args.data_test = 'DVD_EVENT_FUSION_GREY'
        args.batch_size = 12
        args.pre_train = '../experiment/swint_hsa_nsf_grey/model/model_best.pt'
        args.dir_data = '/mnt/disk10T/shangwei/data/deblur/CED/train'
        args.dir_data2 = '/mnt/disk10T/shangwei/data/deblur/GOPRO_Random/train'
        args.dir_data_test = '/mnt/disk10T/shangwei/data/deblur/Real-event-data/val'
        args.n_colors = 1
        args.n_GPUs = 2
    elif args.template == 'SWINT_HSA_NSF_GREY':
        args.task = "VideoDeblur"
        args.model = "SWINT_HSA_NSF_OFFICAL"
        args.n_sequence = 5
        args.patch_size = 180
        args.n_frames_per_video = 200
        args.n_feat = 32
        args.n_resblock = 3
        args.size_must_mode = 20
        args.loss = '1*L1+2*HEM'
        args.lr = 1e-4
        args.lr_decay = 200
        args.window_size = 5
        args.depths = [6, 6, 6, 6, 6, 6]
        args.embed_dim = 256
        args.num_heads = [8, 8, 8, 8, 8, 8]
        args.mlp_ratio = 2
        args.epochs = 500
        args.resi_connection = "1conv"
        args.data_train = 'DVD_FUSION_GREY'
        args.data_test = 'DVD_FUSION_GREY'
        args.batch_size = 12
        # args.pre_train = '/media/r/sw/code/CDVD-TSP-master/experiment/swint_hsa_nsf_event/model/model_best.pt'
        args.dir_data = '/mnt/disk10T/shangwei/data/deblur/CED/train'
        args.dir_data2 = '/mnt/disk10T/shangwei/data/deblur/train'
        args.dir_data_test = '/mnt/disk10T/shangwei/data/deblur/Real-event-data/val'
        args.n_colors = 1
        args.n_GPUs = 2
    elif args.template == 'SWINT_HSA_NSF_REDS_finetune':
        args.task = "VideoDeblur"
        args.model = "SWINT_HSA_NSF"
        args.n_sequence = 3
        args.patch_size = 200
        args.n_frames_per_video = 200
        args.n_feat = 32
        args.n_resblock = 3
        args.size_must_mode = 4
        args.loss = '1*L1+2*HEM'
        args.lr = 1e-6
        args.lr_decay = 2
        args.window_size = 5
        args.depths = [6, 6, 6, 6, 6, 6]
        args.embed_dim = 256
        args.num_heads = [8, 8, 8, 8, 8, 8]
        args.mlp_ratio = 2
        args.resi_connection = "1conv"
        args.data_train = 'DVD_NFS_FUSION'
        args.data_test = 'DVD_NFS_FUSION'
        args.batch_size = 12
        args.epochs = 5
        args.pre_train = '../experiment/swint_hsa_nsf_reds/model/model_best.pt'
        args.dir_data = '/mnt/disk10T/shangwei/data/deblur/REDS_8x_Random/train'
        args.dir_data_test = '/mnt/disk10T/shangwei/data/deblur/BSDval'
    else:
        raise NotImplementedError('Template [{:s}] is not found'.format(args.template))
